"use client";

import { ClockCounterClockwise } from "@phosphor-icons/react";
import { useEffect, useState } from "react";

import { adminAPI, type AdminActivity } from "@/features/admin/admin-api";

export function ActivityManager() {
  const [items,setItems]=useState<AdminActivity[]>([]);const [cursor,setCursor]=useState<string>();const [more,setMore]=useState(false);const [pending,setPending]=useState(false);const [error,setError]=useState("");const [eventType,setEventType]=useState("");const [entityType,setEntityType]=useState("");
  async function load(next?:string,append=false){setPending(true);setError("");try{const response=await adminAPI.listActivities({eventType:eventType||undefined,entityType:entityType||undefined,cursor:next});setItems((current)=>append?[...current,...response.data]:response.data);setCursor(response.meta.page.nextCursor??undefined);setMore(response.meta.page.hasMore);}catch(value){setError(value instanceof Error?value.message:"Aktivitas tidak dapat dimuat.");}finally{setPending(false);}}
  useEffect(()=>{let active=true;adminAPI.listActivities().then((response)=>{if(!active)return;setItems(response.data);setCursor(response.meta.page.nextCursor??undefined);setMore(response.meta.page.hasMore);},(value)=>{if(active)setError(value instanceof Error?value.message:"Aktivitas tidak dapat dimuat.")});return()=>{active=false};},[]);
  return <div className="admin-page-stack"><header className="admin-page-header"><div><p className="admin-kicker">Audit append-only</p><h1>Aktivitas CMS</h1><p>Viewer hanya menampilkan field allowlist. Metadata internal dan PII tidak diekspos.</p></div></header><form className="admin-filter-row" action={()=>void load()}><label className="admin-field"><span>Event type</span><input value={eventType} pattern="[a-z][a-z0-9._-]+" placeholder="product.published" onChange={(event)=>setEventType(event.target.value)}/></label><label className="admin-field"><span>Entity type</span><input value={entityType} pattern="[a-z][a-z0-9._-]+" placeholder="product" onChange={(event)=>setEntityType(event.target.value)}/></label><button className="admin-primary-button" disabled={pending}>Terapkan filter</button></form><p className="admin-status-message" aria-live="polite">{error}</p>{items.length?<ol className="admin-activity-list">{items.map((item)=><li key={item.id}><span className="admin-activity-marker"/><div><h2>{item.eventType}</h2><p>{item.entityType}{item.entityId?` | ${item.entityId}`:""}</p><small>{item.actorType} | {new Date(item.createdAt).toLocaleString("id-ID")}</small></div></li>)}</ol>:!pending?<section className="admin-empty-state"><ClockCounterClockwise size={30}/><h2>Belum ada aktivitas</h2><p>Terapkan filter atau tunggu operasi CMS.</p></section>:null}{more?<button className="admin-secondary-button admin-load-more" disabled={pending} onClick={()=>void load(cursor,true)}>Muat berikutnya</button>:null}</div>;
}
