"use client";

import { ArrowSquareOut, Check, FloppyDisk, Globe, Prohibit } from "@phosphor-icons/react";
import Link from "next/link";
import { useEffect, useState } from "react";

import { adminAPI, AdminAPIError, type AdminPage, type AdminPageKey, type AdminRevision, type EditableContent } from "@/features/admin/admin-api";
import { MediaPicker } from "@/features/admin/media-picker";
import { aboutContentSchema, homeContentSchema } from "@/features/content/schemas";

const labels: Record<string,string> = { metadata:"SEO metadata",title:"Judul",description:"Deskripsi",canonicalPath:"Canonical path",openGraphImage:"Gambar Open Graph",hero:"Hero",eyebrow:"Eyebrow",image:"Gambar",actions:"CTA",label:"Label",href:"Tautan",introduction:"Pengantar",id:"ID stabil",heading:"Heading",paragraphs:"Paragraf",featuredProductSlugs:"Slug produk unggulan",guidePreview:"Teaser panduan tauco",aboutPreview:"Teaser tentang kami",sections:"Bagian narasi",relatedLinks:"Tautan terkait",sources:"Sumber",publisher:"Penerbit",url:"URL sumber",src:"Sumber gambar",alt:"Alt text",decorative:"Dekoratif",slug:"Slug",name:"Nama produk",category:"Kategori",summary:"Ringkasan",facts:"Fakta produk",value:"Nilai",usageSuggestions:"Saran penggunaan",priceEstimate:"Estimasi harga",currency:"Mata uang",amount:"Nominal",qualifier:"Jenis harga",purchaseNote:"Catatan pembelian",contactLink:"Tautan kontak",researchEvidence:"Bukti penelitian",scopeNote:"Batas penggunaan data",source:"Sumber penelitian" };

export function ContentEditor({ pageKey }: { pageKey: AdminPageKey }) {
  const [page,setPage]=useState<AdminPage>(); const [current,setCurrent]=useState<AdminRevision>(); const [content,setContent]=useState<EditableContent>(); const [etag,setEtag]=useState(""); const [confirmed,setConfirmed]=useState(false); const [pending,setPending]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{let active=true;adminAPI.getPage(pageKey).then((response)=>{if(!active)return;setPage(response.data);setCurrent(response.data.latestRevision);setContent(structuredClone(response.data.latestRevision.content));setEtag(response.etag);setMessage("");},(error)=>{if(active)setMessage(error instanceof Error?error.message:"Halaman tidak dapat dimuat.")});return()=>{active=false};},[pageKey]);

  function update(path:(string|number)[],value:unknown){if(!content)return;const next=structuredClone(content);let cursor:unknown=next;for(let index=0;index<path.length-1;index+=1){cursor=(cursor as Record<string,unknown>)[String(path[index])];}(cursor as Record<string,unknown>)[String(path.at(-1))]=value;setContent(next);setConfirmed(false);}
  function validate(){const result=(pageKey==="home"?homeContentSchema:aboutContentSchema).safeParse(content);if(!result.success){setMessage(result.error.issues[0]?.message??"Konten belum valid.");return null;}return result.data as EditableContent;}
  async function save(){const valid=validate();if(!valid||!page)return;if(!confirmed){setMessage("Konfirmasi fact-check wajib.");return;}setPending(true);try{const response=await adminAPI.savePageDraft(pageKey,etag,page.latestRevision.id,valid);const nextPage={...page,latestRevision:response.data,revisions:[summary(response.data),...page.revisions]};setPage(nextPage);setCurrent(response.data);setContent(structuredClone(response.data.content));setEtag(response.etag);setConfirmed(false);setMessage(`Draft revision ${response.data.revisionNumber} tersimpan.`);}catch(error){setMessage(error instanceof AdminAPIError&&error.status===412?"Konten telah berubah. Muat ulang sebelum menyimpan.":error instanceof Error?error.message:"Draft gagal disimpan.");}finally{setPending(false);}}
  async function publish(){if(!current||!confirmed)return;setPending(true);try{const response=await adminAPI.publishPage(pageKey,current.id,etag);setCurrent(response.data);setContent(structuredClone(response.data.content));setEtag(response.etag);setPage((value)=>value?{...value,latestRevision:response.data,publishedRevisionId:response.data.id,revisions:[summary(response.data),...value.revisions]}:value);setConfirmed(false);setMessage(`Revision ${response.data.revisionNumber} dipublikasikan pada API lokal.`);}catch(error){setMessage(error instanceof Error?error.message:"Publish gagal.");}finally{setPending(false);}}
  async function unpublish(){if(!page?.publishedRevisionId)return;setPending(true);try{await adminAPI.unpublishPage(pageKey,etag);setPage({...page,publishedRevisionId:null});setMessage("Halaman di-unpublish dari API lokal.");}catch(error){setMessage(error instanceof Error?error.message:"Unpublish gagal.");}finally{setPending(false);}}
  async function openRevision(id:string){setPending(true);try{const response=await adminAPI.getPageRevision(pageKey,id);setCurrent(response.data);setContent(structuredClone(response.data.content));setConfirmed(false);setMessage(`Revision ${response.data.revisionNumber} dibuka. Save Draft akan membuat revision baru.`);}catch(error){setMessage(error instanceof Error?error.message:"Revision tidak dapat dibuka.");}finally{setPending(false);}}
  if(!page||!content||!current)return <div className="admin-page-stack"><p aria-live="polite">{message||"Memuat editor..."}</p></div>;
  return <div className="admin-content-editor"><header className="admin-editor-header"><div><Link href="/admin/content" className="admin-text-button">← Semua halaman</Link><p className="admin-kicker">{pageKey==="home"?"Homepage":"Tentang Kami"}</p><h1>Editor terstruktur</h1><p>Revision {current.revisionNumber} · {current.status}</p></div><div className="admin-editor-actions"><Link className="admin-secondary-button" target="_blank" href={`/admin/preview/page/${current.id}?key=${pageKey}`}><ArrowSquareOut size={18}/> Preview</Link><button className="admin-secondary-button" disabled={pending||!page.publishedRevisionId} onClick={()=>void unpublish()}><Prohibit size={18}/> Unpublish</button><button className="admin-primary-button" disabled={pending||!confirmed} onClick={()=>void publish()}><Globe size={18}/> Publish</button></div></header><p className="admin-status-message" aria-live="polite">{message}</p><div className="admin-editor-layout"><main className="admin-structured-form"><ValueEditor value={content} path={[]} onChange={update}/><label className="admin-fact-check"><input type="checkbox" checked={confirmed} onChange={(event)=>setConfirmed(event.target.checked)}/><span><strong>Fact-check dikonfirmasi</strong> Saya memastikan hanya data terverifikasi yang dimasukkan dan field yang belum terverifikasi tetap dihilangkan.</span></label><button className="admin-primary-button" disabled={pending||!confirmed} onClick={()=>void save()}><FloppyDisk size={19}/>{pending?"Memproses...":"Save Draft"}</button></main><aside className="admin-revision-panel"><h2>Riwayat revision</h2><ol>{page.revisions.map((revision)=><li key={revision.id}><button type="button" aria-current={current.id===revision.id?"true":undefined} onClick={()=>void openRevision(revision.id)}><span>Revision {revision.revisionNumber}</span><small>{revision.status} · {new Date(revision.createdAt).toLocaleString("id-ID")}</small>{page.publishedRevisionId===revision.id?<em><Check size={14}/> live</em>:null}</button></li>)}</ol></aside></div></div>;
}

function summary(revision:AdminRevision){return {id:revision.id,revisionNumber:revision.revisionNumber,status:revision.status,createdBy:revision.createdBy,createdAt:revision.createdAt,publishedAt:revision.publishedAt};}

export function ValueEditor({value,path,onChange}:{value:unknown;path:(string|number)[];onChange:(path:(string|number)[],value:unknown)=>void}){
  if(isImage(value)){const source=value.src;const id=/\/media\/([0-9a-f-]{36})\//.exec(source)?.[1];return <fieldset className="admin-editor-group"><legend>{fieldLabel(path)}</legend><MediaPicker value={id} informativeOnly={path.includes("openGraphImage")} label="Gunakan media berstatus ready" onChange={(media)=>onChange(path,{src:`/api/v1/media/${media.id}/display.webp`,alt:media.decorative?"":media.altText,decorative:media.decorative})}/><label className="admin-field"><span>Alt text</span><input type="text" value={value.alt} disabled={value.decorative} onChange={(event)=>onChange([...path,"alt"],event.target.value)}/></label><p className="admin-field-note">Source: <code>{source}</code></p></fieldset>}
  if(Array.isArray(value)){return <fieldset className="admin-editor-group"><legend>{fieldLabel(path)}</legend>{value.map((item,index)=><ValueEditor key={`${path.join("-")}-${index}`} value={item} path={[...path,index]} onChange={onChange}/>)}</fieldset>}
  if(value&&typeof value==="object"){return <fieldset className="admin-editor-group"><legend>{fieldLabel(path)}</legend>{Object.entries(value).map(([key,child])=><ValueEditor key={key} value={child} path={[...path,key]} onChange={onChange}/>)}</fieldset>}
  if(typeof value==="boolean")return <label className="admin-check-field"><input type="checkbox" checked={value} onChange={(event)=>onChange(path,event.target.checked)}/><span>{fieldLabel(path)}</span></label>;
  if(typeof value==="number")return <label className="admin-field"><span>{fieldLabel(path)}</span><input type="number" min="0" value={value} onChange={(event)=>onChange(path,event.target.valueAsNumber)}/></label>;
  const text=String(value??"");const multiline=text.length>100||path.includes("paragraphs")||path.at(-1)==="description";return <label className="admin-field"><span>{fieldLabel(path)}</span>{multiline?<textarea value={text} rows={Math.min(6,Math.max(3,Math.ceil(text.length/80)))} onChange={(event)=>onChange(path,event.target.value)}/>:<input type="text" value={text} onChange={(event)=>onChange(path,event.target.value)}/>}</label>;
}
function fieldLabel(path:(string|number)[]){const last=path.at(-1);if(last===undefined)return"Konten halaman";if(typeof last==="number")return`Item ${last+1}`;return labels[last]??last.replace(/([A-Z])/g," $1");}
function isImage(value:unknown):value is {src:string;alt:string;decorative:boolean}{return Boolean(value&&typeof value==="object"&&"src"in value&&"alt"in value&&"decorative"in value);}
