"use client";

import { EnvelopeSimple, SpinnerGap } from "@phosphor-icons/react";
import Link from "next/link";
import { useEffect, useState } from "react";

import { adminAPI, type AdminContactMessage, type AdminContactStatus } from "@/features/admin/admin-api";

export function InboxManager() {
  const [messages,setMessages]=useState<AdminContactMessage[]>([]);const [status,setStatus]=useState<AdminContactStatus|"">("");const [cursor,setCursor]=useState<string>();const [more,setMore]=useState(false);const [pending,setPending]=useState(false);const [error,setError]=useState("");
  async function load(next?:string,append=false){setPending(true);setError("");try{const response=await adminAPI.listContactMessages({status:status||undefined,cursor:next});setMessages((items)=>append?[...items,...response.data]:response.data);setCursor(response.meta.page.nextCursor??undefined);setMore(response.meta.page.hasMore);}catch(value){setError(value instanceof Error?value.message:"Inbox tidak dapat dimuat.");}finally{setPending(false);}}
  useEffect(()=>{let active=true;adminAPI.listContactMessages({status:status||undefined}).then((response)=>{if(!active)return;setMessages(response.data);setCursor(response.meta.page.nextCursor??undefined);setMore(response.meta.page.hasMore);setError("");},(value)=>{if(active)setError(value instanceof Error?value.message:"Inbox tidak dapat dimuat.")});return()=>{active=false};},[status]);
  return <div className="admin-page-stack"><header className="admin-page-header"><div><p className="admin-kicker">Pesan lokal</p><h1>Inbox kontak</h1><p>GET tidak mengubah status. Buka pesan lalu gunakan aksi eksplisit.</p></div><label className="admin-filter"><span>Status</span><select value={status} onChange={(event)=>setStatus(event.target.value as AdminContactStatus|"")}><option value="">Semua</option><option value="unread">Unread</option><option value="read">Read</option><option value="archived">Archived</option></select></label></header><p className="admin-status-message" aria-live="polite">{error}</p>{messages.length?<div className="admin-inbox-list">{messages.map((message)=><article key={message.id}><div><span className={`admin-status-chip is-${message.status}`}>{message.status}</span><h2>{message.subject}</h2><p>{message.name} | {message.email}</p><small>{new Date(message.createdAt).toLocaleString("id-ID")}</small></div><Link className="admin-secondary-button" href={`/admin/inbox/${message.id}`}>Buka pesan</Link></article>)}</div>:!pending?<section className="admin-empty-state"><EnvelopeSimple size={30}/><h2>Inbox kosong</h2><p>Belum ada pesan pada filter ini.</p></section>:null}{more?<button className="admin-secondary-button admin-load-more" disabled={pending} onClick={()=>void load(cursor,true)}>{pending?<SpinnerGap className="admin-spin"/>:null}Muat berikutnya</button>:null}</div>;
}

export function InboxDetail({ id }:{id:string}) {
  const [message,setMessage]=useState<AdminContactMessage>();const [etag,setEtag]=useState("");const [pending,setPending]=useState(false);const [notice,setNotice]=useState("");
  useEffect(()=>{adminAPI.getContactMessage(id).then((response)=>{setMessage(response.data);setEtag(response.etag)},(error)=>setNotice(error instanceof Error?error.message:"Pesan tidak ditemukan."));},[id]);
  async function update(status:AdminContactStatus){if(!message)return;setPending(true);try{const response=await adminAPI.updateContactMessageStatus(id,etag,status);setMessage(response.data);setEtag(response.etag);setNotice(`Status diubah menjadi ${status}.`);}catch(error){setNotice(error instanceof Error?error.message:"Status gagal diubah.");}finally{setPending(false);}}
  if(!message)return <div className="admin-page-stack"><p aria-live="polite">{notice||"Memuat pesan..."}</p></div>;
  return <div className="admin-page-stack"><header className="admin-page-header"><div><Link className="admin-text-button" href="/admin/inbox">Kembali ke inbox</Link><p className="admin-kicker">{message.status}</p><h1>{message.subject}</h1><p>Diterima {new Date(message.createdAt).toLocaleString("id-ID")}</p></div></header><section className="admin-message-detail"><dl><div><dt>Nama</dt><dd>{message.name}</dd></div><div><dt>Email</dt><dd><a href={`mailto:${message.email}`}>{message.email}</a></dd></div>{message.phone?<div><dt>Telepon</dt><dd>{message.phone}</dd></div>:null}</dl><div className="admin-message-body"><h2>Pesan</h2><p>{message.message}</p></div><div className="admin-editor-actions" aria-label="Ubah status pesan"><button className="admin-secondary-button" disabled={pending||message.status==="unread"} onClick={()=>void update("unread")}>Tandai unread</button><button className="admin-primary-button" disabled={pending||message.status==="read"} onClick={()=>void update("read")}>Tandai read</button><button className="admin-secondary-button" disabled={pending||message.status==="archived"} onClick={()=>void update("archived")}>Archive</button></div></section><p className="admin-status-message" aria-live="polite">{notice}</p></div>;
}
