package application

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/ilhamnugraha8944/tauco/backend/internal/media/domain"
)

const (
	MaxUploadBytes       = 10 << 20
	MaxStoredObjectBytes = 64 << 20
)

var (
	ErrUploadIntentNotFound        = errors.New("media upload intent not found")
	ErrUploadIntentConflict        = errors.New("media upload intent state conflict")
	ErrUploadIntentMetadata        = errors.New("media upload metadata does not match intent")
	ErrUploadIntentCleanupConflict = errors.New("media upload intent cleanup conflict")
	ErrInvalidMediaSource          = errors.New("invalid media source")
)

var (
	ErrObjectTooLarge = errors.New("media object exceeds the allowed size")
	ErrObjectNotFound = errors.New("media object not found")
)

type ObjectStore interface {
	PutIfAbsent(context.Context, string, string, []byte) error
	Get(context.Context, string) ([]byte, error)
}

type ObjectInfo struct {
	Bytes    int64
	MIMEType string
	SHA256   string
}

type PresignedUpload struct {
	URL       string
	Headers   map[string]string
	ExpiresAt time.Time
}

// QuarantineStore is the small capability set required by direct media
// uploads. Object keys are generated by the server and never accepted from a
// browser.
type QuarantineStore interface {
	ObjectStore
	PresignPut(context.Context, string, string, string, int64, time.Duration) (PresignedUpload, error)
	Head(context.Context, string) (ObjectInfo, error)
	GetBounded(context.Context, string, int64) ([]byte, error)
	Delete(context.Context, string) error
	Health(context.Context) error
}

type HealthStore interface {
	Health(context.Context) error
}

type ObjectDeleter interface {
	Delete(context.Context, string) error
}

type NormalizedImage struct {
	Data          []byte
	MIME          string
	Width, Height int
	SHA256        string
}

type GeneratedVariant struct {
	Data          []byte
	Width, Height int
	SHA256        string
}

type Processor interface {
	Normalize([]byte) (NormalizedImage, error)
	Variants([]byte) ([]GeneratedVariant, []int, error)
}

type Repository interface {
	CreateProcessing(context.Context, domain.Asset) (string, bool, error)
	Load(context.Context, string) (domain.Asset, error)
	MarkReady(context.Context, string, []domain.Variant, []int) error
	MarkFailed(context.Context, string, string) error
}

type UploadIntentRepository interface {
	CreateUploadIntent(context.Context, domain.UploadIntentDraft) (domain.UploadIntent, error)
	GetUploadIntent(context.Context, string) (domain.UploadIntent, error)
	QueueUploadIntent(context.Context, string, string, int64, string) (domain.UploadIntent, bool, error)
	CompleteUploadIntent(context.Context, string, string) error
	FailUploadIntent(context.Context, string, string) error
	ClaimUploadIntentCleanup(context.Context, int) ([]domain.UploadIntent, error)
	CompleteUploadIntentCleanup(context.Context, string) error
}

type Ingestor struct {
	repository Repository
	store      ObjectStore
	processor  Processor
}

func NewIngestor(repository Repository, store ObjectStore, processor Processor) (*Ingestor, error) {
	if repository == nil || store == nil || processor == nil {
		return nil, errors.New("media ingestor requires repository, storage, and processor")
	}
	return &Ingestor{repository: repository, store: store, processor: processor}, nil
}

func (ingestor *Ingestor) Ingest(ctx context.Context, source []byte, alt string, decorative bool) (string, bool, error) {
	if len(source) == 0 || len(source) > MaxUploadBytes {
		return "", false, fmt.Errorf("%w: source must be between 1 byte and 10 MiB", ErrInvalidMediaSource)
	}
	normalized, err := ingestor.processor.Normalize(source)
	if err != nil {
		return "", false, fmt.Errorf("%w: %v", ErrInvalidMediaSource, err)
	}
	if len(normalized.Data) > MaxStoredObjectBytes {
		return "", false, fmt.Errorf("%w: normalized image exceeds 64 MiB", ErrInvalidMediaSource)
	}
	key := fmt.Sprintf("media/original/%s.png", normalized.SHA256)
	asset := domain.Asset{
		Status: domain.StatusProcessing, OriginalKey: key,
		OriginalMIME: normalized.MIME, OriginalWidth: normalized.Width,
		OriginalHeight: normalized.Height, OriginalBytes: int64(len(normalized.Data)),
		SHA256: normalized.SHA256, AltText: alt, Decorative: decorative,
	}
	if err := asset.Validate(); err != nil {
		return "", false, fmt.Errorf("%w: %v", ErrInvalidMediaSource, err)
	}
	if err := ingestor.store.PutIfAbsent(ctx, key, normalized.MIME, normalized.Data); err != nil {
		return "", false, fmt.Errorf("store normalized media: %w", err)
	}
	return ingestor.repository.CreateProcessing(ctx, asset)
}

type VariantHandler struct {
	repository Repository
	store      ObjectStore
	processor  Processor
}

func NewVariantHandler(repository Repository, store ObjectStore, processor Processor) (*VariantHandler, error) {
	if repository == nil || store == nil || processor == nil {
		return nil, errors.New("media variant handler requires repository, storage, and processor")
	}
	return &VariantHandler{repository: repository, store: store, processor: processor}, nil
}

func (handler *VariantHandler) Handle(ctx context.Context, payload json.RawMessage) error {
	var body struct {
		MediaAssetID string `json:"mediaAssetId"`
	}
	if err := json.Unmarshal(payload, &body); err != nil || body.MediaAssetID == "" {
		return errors.New("invalid media job payload")
	}
	asset, err := handler.repository.Load(ctx, body.MediaAssetID)
	if err != nil {
		return err
	}
	source, err := handler.store.Get(ctx, asset.OriginalKey)
	if err != nil {
		_ = handler.repository.MarkFailed(ctx, asset.ID, "ORIGINAL_READ_FAILED")
		return err
	}
	generated, skipped, err := handler.processor.Variants(source)
	if err != nil {
		_ = handler.repository.MarkFailed(ctx, asset.ID, "VARIANT_PROCESSING_FAILED")
		return err
	}
	variants := make([]domain.Variant, 0, len(generated))
	for _, item := range generated {
		key := fmt.Sprintf("media/variant/%s/w%d.webp", asset.SHA256, item.Width)
		if err := handler.store.PutIfAbsent(ctx, key, "image/webp", item.Data); err != nil {
			_ = handler.repository.MarkFailed(ctx, asset.ID, "VARIANT_STORE_FAILED")
			return err
		}
		variants = append(variants, domain.Variant{
			Width: item.Width, Height: item.Height, ObjectKey: key,
			MIME: "image/webp", Bytes: int64(len(item.Data)), SHA256: item.SHA256,
		})
	}
	return handler.repository.MarkReady(ctx, asset.ID, variants, skipped)
}
